# Generated by Django 5.1.2 on 2024-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='preview_clip',
            field=models.FileField(null=True, upload_to='audio_previews/'),
        ),
    ]
