# Generated by Django 5.1.2 on 2024-11-03 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_album_preview_clip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('preview_clip', models.FileField(null=True, upload_to='track_previews/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='shop.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.artist')),
            ],
        ),
    ]
