# Generated by Django 5.1.2 on 2025-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
