# Generated by Django 5.1.2 on 2025-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='ambient_covers/')),
                ('preview_clip', models.FileField(null=True, upload_to='ambient_previews/')),
                ('release_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
