# Generated by Django 5.1.2 on 2025-02-23 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_ambient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambient',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.artist'),
        ),
    ]
