# Generated by Django 5.1.2 on 2026-08-15 20:42

import django.db.models.deletion
import shop.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_checkout_email_order_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='download_file',
            field=models.FileField(blank=True, null=True, storage=shop.storage.PrivateDownloadStorage(), upload_to='tracks/'),
        ),
        migrations.CreateModel(
            name='DigitalEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_type', models.CharField(choices=[('album', 'Album'), ('track', 'Track')], max_length=20)),
                ('product_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_entitlements', to='shop.order')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_entitlement', to='shop.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
